### ISSUE TITLE
NullReferenceException in GlowWindowBehavior.AssociatedObjectStateChanged when restoring the window

### ISSUE THREAD

**Issue by Epix37** [MahApps/MahApps.Metro#1703]
Version 1.0, seemed to be working fine with 0.13.

This seems to be happening when setting `WindowState = WindowState.Normal`, when previously it was set to `WindowState.Minimized` and `Hide()` was called. (Restore via tray icon in this case)

> System.NullReferenceException: Object reference not set to an instance of an object.
at MahApps.Metro.Behaviours.GlowWindowBehavior.AssociatedObjectStateChanged(Object sender, EventArgs e)
at System.EventHandler.Invoke(Object sender, EventArgs e)
at System.Windows.Window.OnStateChanged(EventArgs e)
at System.Windows.Window.WmSizeChanged(IntPtr wParam)
at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by punker76** [comment]
this should be fixed with 1.1.0 (and current alpha)
