### ISSUE TITLE
Design time problem with subclasses of CustomDialog

### ISSUE THREAD

**Issue by superlloyd** [MahApps/MahApps.Metro#1895]
Hi,

I am trying to design a custom metro dialog in XAML, as in:
```
<mad:CustomDialog 
    x:Class="MNetMobile.MDTClient.Views.NewIncidentDialog"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mad="clr-namespace:MahApps.Metro.Controls.Dialogs;assembly=MahApps.Metro"
    >
</mad:CustomDialog>
```

Unfortunately the design area is broken with the GetBaseException() being: `NullReferenceException`
```
   at MahApps.Metro.Controls.Dialogs.BaseMetroDialog.HandleTheme()
   at MahApps.Metro.Controls.Dialogs.BaseMetroDialog.Initialize()
   at MahApps.Metro.Controls.Dialogs.BaseMetroDialog..ctor()
   at MahApps.Metro.Controls.Dialogs.CustomDialog..ctor()
```

**Comment by punker76** [comment]
@superlloyd this is fixed in the latest alpha version

**Comment by superlloyd** [comment]
Cool, thanks! :)
