### ISSUE TITLE
CTD on Application Open

### ISSUE THREAD

**Issue by seandevenish** [MahApps/MahApps.Metro#1999]
My application has been running Mahapps without problems, initially with 0.14.0-ALPHA30, which I then upgraded to 1.1.2. These both worked fine, but because of a bug with dialogs in 1.1.2 I necessarily upgraded 1.1.3 ALPHA068 and also just tried the latest build 1.1.3-ALPH087.

These two new versions fix the dialog bug, and work fine on most installs, but I have had two users on Windows 7 experiencing a crash on application startup, windows error details as follows:

Problem signature:
  Problem Event Name:                        CLR20r3
  Problem Signature 01:                       <My application>
  Problem Signature 02:                       <my app version>
  Problem Signature 03:                       55812230
  Problem Signature 04:                       MahApps.Metro
  Problem Signature 05:                       1.1.3.68
  Problem Signature 06:                       55732d61
  Problem Signature 07:                       88f
  Problem Signature 08:                       97
  Problem Signature 09:                       System.Windows.Markup.XamlParse
  OS Version:                                          6.1.7601.2.1.0.256.48
  Locale ID:                                             3081
  Additional Information 1:                  0a9e
  Additional Information 2:                  0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:                  0a9e
  Additional Information 4:                  0a9e372d3b4ad19135b953a78882e789

Problem Signature 07: 88f appears to refer to the constructor for the SystemParameters2 class... Short of downgrading back down to 0.14.0-ALPHA30, is this a known issue and/or is there a fix in the pipeline? 

Note I have tested with my current code-base but with a reinstalled 0.14.0-ALPHA30 Mahapps.Metro and the application no longer crashes, so it seems to be specifically related to the most recent versions of Mahapps.

Error event logs for the application are below:

Log Name:      Application
Source:        .NET Runtime
Date:          22/06/2015 9:21:09 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      PCName
Description:
Application: My application
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at MyApplication.MainWindow.InitializeComponent()
   at MyApplication.MainWindow..ctor()
   at MyApplication.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at MyApplication.App.Main()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-06-21T23:21:09.000000000Z" />
    <EventRecordID>91210</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC Name</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: My application name
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadComponent(System.Object, System.Uri)
   at MyApplication.MainWindow.InitializeComponent()
   at MyApplication.MainWindow..ctor()
   at MyApplication.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.&lt;.ctor&gt;b__1(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at MyApplication.App.Main()
</Data>
  </EventData>
</Event>

AND

Log Name:      Application
Source:        Application Error
Date:          22/06/2015 9:21:11 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      PCName
Description:
Faulting application name: My application, my application version, time stamp: 0x5583c6cf
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18409, time stamp: 0x53159a86
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0x23530
Faulting application start time: 0x01d0ac78f4a04b25
Faulting application path: My application path
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 33b10985-186c-11e5-bd39-7446a0b91287
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-06-21T23:21:11.000000000Z" />
    <EventRecordID>91211</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC Name</Computer>
    <Security />
  </System>
  <EventData>
    <Data>My application</Data>
    <Data>My application version</Data>
    <Data>5583c6cf</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.18409</Data>
    <Data>53159a86</Data>
    <Data>e0434352</Data>
    <Data>0000c42d</Data>
    <Data>23530</Data>
    <Data>01d0ac78f4a04b25</Data>
    <Data>My application path</Data>
    <Data>C:\Windows\syswow64\KERNELBASE.dll</Data>
    <Data>33b10985-186c-11e5-bd39-7446a0b91287</Data>
  </EventData>
</Event>

**Comment by punker76** [comment]
@seandevenish is it possible to give us the inner exception of the `System.Windows.Markup.XamlParseException`. there is maybe a change in a helper class or somethonge else that causes the crash.

**Comment by seandevenish** [comment]
Unfortunately it is on a user machine so I don't have an ability to debug directly. I also use Raygun for error reporting (which also captures unhandled exceptions), unfortunately nothing is submitted because the error occurs before it is initiailsed...

**Comment by punker76** [comment]
@seandevenish damn! :-(

**Comment by seandevenish** [comment]
Issue resolved: had the user install the latest version of .Net and it loads fine

**Comment by punker76** [comment]
@seandevenish crazy, what .Net was installed?

**Comment by seandevenish** [comment]
didn't check, just installed 4.5.2 to fix it... I didn't think they would have been too out of date though, they run some other fairly heavy duty applications that rely on the .net assemblies.
