### ISSUE TITLE
Error on open from thread

### ISSUE THREAD

**Issue by Pekshev** [MahApps/MahApps.Metro#2005]
Hello.
The error does not appear to me. Error occurs in one of the users. The error appears when you open the window from another thread
```
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
at MahApps.Metro.Controls.MetroWindow.get_Flyouts()
at MahApps.Metro.Controls.MetroWindow.ThemeManagerOnIsThemeChanged(Object sender, OnThemeChangedEventArgs e)
at MahApps.Metro.Controls.SafeRaise.Raise[T](EventHandler`1 eventToRaise, Object sender, T args)
at MahApps.Metro.ThemeManager.OnThemeChanged(Accent newAccent, AppTheme newTheme)
at MahApps.Metro.ThemeManager.ChangeAppStyle(ResourceDictionary resources, Tuple`2 oldThemeInfo, Accent newAccent, AppTheme newTheme)
at MahApps.Metro.ThemeManager.ChangeAppStyle(Window window, Accent newAccent, AppTheme newTheme)
at mpMsg.WindowHelpers.ChangeWindowTheme(String theme, String accentColor, MetroWindow window)
at mpMsg.WindowHelpers.OnWindowStartUp(MetroWindow window, String theme, String accentColor, String borderType)
at mpMsg.MpExWin..ctor(Exception exc)
at mpMsg.MpExWin.Show(Exception exception)
at ModPlus.ModPlus.CheckForNewFunctions()
at ModPlus.ModPlus.WorkAll()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by shiftkey** [comment]
> The error appears when you open the window from another thread

You're going to have a bad time doing this from a background thread (because of the [MTA/STA](http://stackoverflow.com/a/127240/1363815) differences). It's a really important thing to keep in mind when you're manipulating objects in a WPF view.

If you *really* want to launch the Window from a different thread, you need to think about doing something like this ([citation](http://reedcopsey.com/2011/11/28/launching-a-wpf-window-in-a-separate-thread-part-1/)):

```csharp
// Create a thread
Thread newWindowThread = new Thread(new ThreadStart( () =>
{
    // Create and show the Window
    Window1 tempWindow = new Window1();
    tempWindow.Show();
    // Start the Dispatcher Processing
    System.Windows.Threading.Dispatcher.Run();
}));
// Set the apartment state
newWindowThread.SetApartmentState(ApartmentState.STA);
// Make the thread a background thread
newWindowThread.IsBackground = true;
// Start the thread
newWindowThread.Start();
```

Without extra details on how the window is being launched, that's the best advice I can provide.

**Comment by Pekshev** [comment]
Funny, but I'm doing the same)
``` C#
public static Thread Worker;
        public static void StartTimer()
        {
            Worker = new Thread(WorkAll);
            Worker.SetApartmentState(ApartmentState.STA);
            Worker.IsBackground = true;
            Worker.Start();
        }

        private static void WorkAll()
        {
            while (true)
            {
                Thread.Sleep(Intervals[MpVars.CheckSpan]);
                if (MpVars.CheckNew)
                    CheckForNewFunctions();
                if (MpVars.CheckUpdates)
                    CheckForUpdates();
            }
        }
private static void CheckForNewFunctions()
        {
            try
            {
                ................
                    if (resultEl.Elements("function").Any())
                    {
                        NewFunctionsShow win = new NewFunctionsShow
                        {
                            LbFunctions = { ItemsSource = resultEl.Elements("function") }
                        };
                        win.ShowDialog();
                    }

                }
            }
            catch (System.Exception exception)
            {
                MpExWin.Show(exception);
            }
        }
```

**Comment by shiftkey** [comment]
@Pekshev there's a lot of code here that's unrelated to MahApps.Metro. Do you have a demo project which shows the problem in isolation, so we can understand the situation better?

**Comment by Pekshev** [comment]
The problem is that I do plug-in for AutoCad. And personally I do not have this error. Problem is, the other user
I'll try to make a separate project with such actions. If the error is, then it's a project here

**Comment by shiftkey** [comment]
> I'll try to make a separate project with such actions. If the error is, then it's a project here

I understand. Please let us know if you're able to recreate the issue in isolated.
