### ISSUE TITLE
ShowMetroDialogAsync for CustomDialog fails to show and throws null ref exception

### ISSUE THREAD

**Issue by kai33** [MahApps/MahApps.Metro#2158]
using MahApps.Metro.1.1.3-ALPHA196

stacktrace:
   at MahApps.Metro.Controls.Dialogs.BaseMetroDialog.HandleTheme() in c:\TeamCity\buildAgent\work\b90af7509433a217\MahApps.Metro\Controls\Dialogs\BaseMetroDialog.cs:line 138
   at MahApps.Metro.Controls.Dialogs.BaseMetroDialog.<Initialize>b__4(Object sender, RoutedEventArgs args) in c:\TeamCity\buildAgent\work\b90af7509433a217\MahApps.Metro\Controls\Dialogs\BaseMetroDialog.cs:line 103
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

cause:
https://github.com/MahApps/MahApps.Metro/blob/39d9a9a19a53ce6014ef2bbbde1ab916bfc75818/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs#L138
this.OwningWindow is null, and Application.Current is null also (I'm developing an office add-in)

temp workaround:
inherit BaseMetroDialog, and pass MetroWindow to its constructor to set OwningWindow;
or use reflection to set OwningWindow.

**Comment by punker76** [comment]
@kai33 i don't really know how your add in could work....

but the DialogManager provides this method which only works with an 'owner' `Window`

```csharp
public static Task ShowMetroDialogAsync(this MetroWindow window, BaseMetroDialog dialog,
            MetroDialogSettings settings = null)
```

https://github.com/MahApps/MahApps.Metro/blob/39d9a9a19a53ce6014ef2bbbde1ab916bfc75818/MahApps.Metro/Controls/Dialogs/DialogManager.cs#L317

https://github.com/MahApps/MahApps.Metro/blob/39d9a9a19a53ce6014ef2bbbde1ab916bfc75818/MahApps.Metro/Controls/Dialogs/BaseMetroDialog.cs#L65

**Comment by kai33** [comment]
hi I just call the method like this:

(in a MetroWindow, which is created and managed by the add-in)

this.ShowMetroDialogAsync(new CustomDIalog{ TItle = "Hello World" });

then it'll throw the null ref exception, and the dialog fails to show up.
I've to set dialog's OwningWindow to this MetroWindow in order to make it work

**Comment by punker76** [comment]
@kai33 Is this still an issue for you (latest source or pre-release)? If not then feel free to close this one.
