### ISSUE TITLE
DialogManager throws InvalidOperationException when DialogMessage is shown in second time (Threads and SimpleChildWindow involved)

### ISSUE THREAD

**Issue by jonny123d** [MahApps/MahApps.Metro#2321]
Hello,
I have been being a problem with message dialogs when I'm using threads and child windows. Here is exception's information:

```
System.InvalidOperationException
   
Message:
   Sequence contains more than one element
   
StackTrace:
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at MahApps.Metro.Controls.Dialogs.DialogManager.AddDialog(MetroWindow window, BaseMetroDialog dialog) in C:\Users\punker76\Documents\GitHub\MahApps.Metro\MahApps.Metro\Controls\Dialogs\DialogManager.cs:line 423
   at MahApps.Metro.Controls.Dialogs.DialogManager.SetupAndOpenDialog(MetroWindow window, BaseMetroDialog dialog) in C:\Users\punker76\Documents\GitHub\MahApps.Metro\MahApps.Metro\Controls\Dialogs\DialogManager.cs:line 413
   at MahApps.Metro.Controls.Dialogs.DialogManager.<>c__DisplayClass2_0.<ShowMessageAsync>b__1() in C:\Users\punker76\Documents\GitHub\MahApps.Metro\MahApps.Metro\Controls\Dialogs\DialogManager.cs:line 172
   at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
```

This is my environment:
- Windows 8.1 Pro (64 bits)
- Visual Studio Ultimate 2013 Update 4

I'm using Mahapps stable libraies:
- Mahapps.Metro 1.2.2.0
- Mahapps.Metro.SimpleChildWindow 1.2.0.0

I developed an application to show that:
http://1drv.ms/1PZTAu1

There are 4 buttons or steps. You can reproduce the issue in 4 ways, following one of these steps sequences (only clicking step buttons and closing message dialogs):
- 1, 2, 2.
- 1, 2, 3, 4.
- 4, 4.
- 4, 1, 2.

Due to SimpleChildWindow is involved, I will open another issue in it's repository.
I think it is related with this issue but I'm not sure: https://github.com/MahApps/MahApps.Metro/issues/2309

**Comment by thoemmi** [comment]
@punker76 I guess that's an issue in SimpleChildWindow. Since a09542fa there must be only one child in the `PART_MetroActiveDialogContainer` container. Inside to MahAppsMetro this is managed by  `DialogManager.AddDialog`/`RemoveDialog`.
However the SimpleChildWindow library circumvents this and tries to access `PART_MetroActiveDialogContainer` [directly](https://github.com/punker76/MahApps.Metro.SimpleChildWindow/blob/master/MahApps.Metro.SimpleChildWindow/MahApps.Metro.SimpleChildWindow/ChildWindowManager.cs#L42-L43).

**Comment by thoemmi** [comment]
@punker76 I changed SimpleChildWindow to use `PART_Metro**Inactive**DialogsContainer` instead of `PART_Metro**Active**DialogContainer`. This way @jonny123d's projects runs all of his use cases without a flaw (though I didn't check if the `ChildWindow`s are still in the container after closing)

**Comment by punker76** [comment]
@thoemmi So it's better you create a PR :-)

**Comment by thoemmi** [comment]
Here you go :grin:

**Comment by jonny123d** [comment]
Thank you @thoemmi for your time checking this issue, I hope this will fix the problem in my projects.

**Comment by punker76** [comment]
should be fixed with MahApps.Metro.SimpleChildWindow v1.3.0 and MahApps.Metro v1.2.3
