### ISSUE TITLE
ShowMessageAsync Exception

### ISSUE THREAD

**Issue by ramiroreal** [MahApps/MahApps.Metro#2411]
## What steps will reproduce this issue?
On the constructor of the main window, there is a try catch block (development is on an early stage), inside the catch block there is an invocation to show a message (this.ShowMessageAsync("Warning",Issues were found....").
## _Write problem description here_
Exception details:
   at MahApps.Metro.Controls.Dialogs.DialogManager.HandleOverlayOnShow(MetroDialogSettings settings, MetroWindow window) in C:\Users\punker76\Documents\GitHub\MahApps.Metro\MahApps.Metro\Controls\Dialogs\DialogManager.cs:line 295
   at MahApps.Metro.Controls.Dialogs.DialogManager.ShowMessageAsync(MetroWindow window, String title, String message, MessageDialogStyle style, MetroDialogSettings settings) in C:\Users\punker76\Documents\GitHub\MahApps.Metro\MahApps.Metro\Controls\Dialogs\DialogManager.cs:line 155
   at Toolkit.MainWindow..ctor() in C:\Users\rreal\Desktop\Toolkit v0.0.0.6\Toolkit\MainWindow.xaml.cs:line 34
### Expected outcome

--
### Environment

- MahApps.Metro __v1.2.4__
- Windows __7__
- Visual Studio __2015__
- .NET Framework __4.6__

**Comment by punker76** [comment]
@ramiroreal maybe it's caused by that you try show something before the window itself is shown. you should try this in the loaded event or later

**Comment by ramiroreal** [comment]
Nice! Thanks for your help sir!
