### ISSUE TITLE
The property IsWindows10OrHigher in BorderlessWindowBehavior throws exception

### ISSUE THREAD

**Issue by ekblom** [MahApps/MahApps.Metro#2662]
## What steps will reproduce this issue?

The property IsWindows10OrHigher in MahApps.Metro/Behaviours/BorderlessWindowBehavior.cs introduced in https://github.com/MahApps/MahApps.Metro/commit/fe7dd828dbc945a705f10be67983a75a147328fc#diff-783a1e5d5018be41e08311212094178e is causing an exception on Windows 10 with Aniversary update. Seems that there are problems with WMI (even when running as administrator..)

Message: Access denied 
Stack Trace: 

   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__92`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at MahApps.Metro.Behaviours.BorderlessWindowBehavior.IsWindows10OrHigher() in C:\TeamCity\buildAgent\work\b90af7509433a217\MahApps.Metro\Behaviours\BorderlessWindowBehavior.cs:line 38
   at MahApps.Metro.Behaviours.BorderlessWindowBehavior.OnAttached() in C:\TeamCity\buildAgent\work\b90af7509433a217\MahApps.Metro\Behaviours\BorderlessWindowBehavior.cs:line 47
   at System.Windows.Interactivity.Behavior.Attach(DependencyObject dependencyObject)
   at System.Windows.Interactivity.BehaviorCollection.ItemAdded(Behavior item)
   at System.Windows.Interactivity.AttachableCollection`1.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction action, Int32 oldIndex, T oldValue, Int32 newIndex, T newValue)
   at System.Windows.FreezableCollection`1.AddHelper(T value)
   at MahApps.Metro.Behaviours.StylizedBehaviors.OnPropertyChanged(DependencyObject dpo, DependencyPropertyChangedEventArgs e) in C:\TeamCity\buildAgent\work\b90af7509433a217\MahApps.Metro\Behaviours\StylizedBehaviors.cs:line 68
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)
   at System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
   at System.Windows.StyleHelper.DoThemeStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldThemeStyle, Style newThemeStyle, Style style)
   at System.Windows.StyleHelper.UpdateThemeStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldThemeStyle, Style newThemeStyle, Style& themeStyleCache)
   at System.Windows.FrameworkElement.OnThemeStyleChanged(DependencyObject d, Object oldValue, Object newValue)
   at System.Windows.StyleHelper.GetThemeStyle(FrameworkElement fe, FrameworkContentElement fce)
   at System.Windows.FrameworkElement.UpdateThemeStyleProperty()
   at System.Windows.FrameworkElement.OnInitialized(EventArgs e)
   at System.Windows.FrameworkElement.TryFireInitialized()
   at System.Windows.FrameworkElement.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(XamlType xamlType, Object obj, Boolean begin)

### Expected outcome

Not causing an exceptoin

--
### Environment

- MahApps.Metro __v1.3.0-ALPHA199__
- Windows __10 with Aniversary update__
- Visual Studio __2015__
- .NET Framework __4.6.1__

**Comment by thoemmi** [comment]
It works fine on my machine, which is running the recent Insider Preview 10.0.14926. So I don't guess that the Anniversary Update is causing this.

**Comment by ekblom** [comment]
Turns out my WMI-repository was corrupt, clearing it and rebooting solved the "Access Denied"-error. So, on a working environment this should never happen, the question is how to handle its when it occurs. Probably it will not happen often enough to take any special measures to prevent the error to crash the application.

Another solution would be getting the os version from registry, from SOFTWARE\Microsoft\WindowsNT\CurrentVersion\CurrentMajorVersionNumber

**Comment by punker76** [comment]
@ekblom The reason why I used the WMI was GetVersionEx is marked as deprecated since Win8.1. I hoped this WMI call is safe enough, but ...
I have this idea for getting the version

- use RtlGetVersion if the WMI call fails
- or use always RtlGetVersion

```csharp
    static class Ntdll
    {
        [StructLayout(LayoutKind.Sequential)]
        public struct OSVERSIONINFOEX
        {
            public uint dwOSVersionInfoSize;
            public uint dwMajorVersion;
            public uint dwMinorVersion;
            public uint dwBuildNumber;
            public uint dwPlatformId;
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)]
            public string szCSDVersion;
            public ushort wServicePackMajor;
            public ushort wServicePackMinor;
            public ushort wSuiteMask;
            public byte wProductType;
            public byte wReserved;
        }

        class NativeMethods
        {
            [DllImport("ntdll.dll", CharSet = CharSet.Unicode)]
            public static extern int RtlGetVersion([In, Out] ref OSVERSIONINFOEX version);
        }

        public static Version RtlGetVersion()
        {
            var v = default(OSVERSIONINFOEX);
            v.dwOSVersionInfoSize = (uint)Marshal.SizeOf(typeof(OSVERSIONINFOEX));
            if (NativeMethods.RtlGetVersion(ref v) == 0)
            {
                return new Version((int)v.dwMajorVersion, (int)v.dwMinorVersion, (int)v.dwBuildNumber, 0);
            }
            // didn't work ???
            return Environment.OSVersion.Version;
        }
    }
```

**Comment by ekblom** [comment]
If WMI fails, it will take a few seconds (at least it did on my machine), so if that call is made often it will make the application really slow.

**Comment by punker76** [comment]
@ekblom Yeah a cache field could be fine...

**Comment by punker76** [comment]
@ekblom oh... it's already cached ;-)

```
this.isWindwos10OrHigher = IsWindows10OrHigher();
```

**Comment by ekblom** [comment]
oh, of course. :)
Then your proposed solution should be fine.  Is BorderlessWindowBehavior instantiated once or multiple times?

**Comment by punker76** [comment]
@ekblom Once for every MetroWindow

**Comment by punker76** [comment]
this?

```csharp
var version = Standard.NtDll.RtlGetVersion();
if (default(Version) == version)
{
    // Snippet from Koopakiller https://dotnet-snippets.de/snippet/os-version-name-mit-wmi/4929
    using (var mos = new ManagementObjectSearcher("SELECT Caption, Version FROM Win32_OperatingSystem"))
    {
        var attribs = mos.Get().OfType<ManagementObject>();
        //caption = attribs.FirstOrDefault().GetPropertyValue("Caption").ToString() ?? "Unknown";
        version = new Version((attribs.FirstOrDefault()?.GetPropertyValue("Version") ?? "0.0.0.0").ToString());
    }
}
return version >= new Version(10, 0);
```

or this?

```csharp
try
{
    // Snippet from Koopakiller https://dotnet-snippets.de/snippet/os-version-name-mit-wmi/4929
    using (var mos = new ManagementObjectSearcher("SELECT Caption, Version FROM Win32_OperatingSystem"))
    {
        var attribs = mos.Get().OfType<ManagementObject>();
        //caption = attribs.FirstOrDefault().GetPropertyValue("Caption").ToString() ?? "Unknown";
        var version = new Version((attribs.FirstOrDefault()?.GetPropertyValue("Version") ?? "0.0.0.0").ToString());
        return version >= new Version(10, 0);
    }
}
catch (Exception)
{
    // bad WMI or access denied
    var version = Standard.NtDll.RtlGetVersion();
    return version >= new Version(10, 0);
}
```

I prefer first one...

/cc @thoemmi

**Comment by punker76** [comment]
@ekblom try 1.3.0-ALPHA200

**Comment by thoemmi** [comment]
@punker76 it depends 😉 Is `RtlGetVersion` reliable enough? Then call that first, like you did in your first proposal.

**Comment by punker76** [comment]
@thoemmi corefx use it too and it's avaible since win2000

**Comment by thoemmi** [comment]
@punker76 I [noticed that too](https://msdn.microsoft.com/en-us/library/mt723418(v=vs.85).aspx). I also checked the [Version Helper functions](https://msdn.microsoft.com/en-us/library/dn424972(v=vs.85).aspx), but to use them your application must be manifested.
Therefore go for `RtlGetVersion` 👍

**Comment by ekblom** [comment]
Unfortunately i was not able to reproduce this error even when reverting back to the old repository for WMI and using ALPHA199. But its working in ALPHA200 too anyway. :)

**Comment by xxMUROxx** [comment]
Sorry, wrong ID-reference in PR and commit
