### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by bbday** [MahApps/MahApps.Metro#2748]
I use last app version on wpf i have this problem sometimes 1 for day when i run app on virtual server (i dont' have this issue in my local pc)

E_ACCESSDENIED
   at Standard.HRESULT.ThrowIfFailed(String message)
   at Standard.HRESULT.ThrowLastError()
   at MahApps.Metro.Controls.GlowWindow.GetRelativeMousePosition()
   at MahApps.Metro.Controls.GlowWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by punker76** [comment]
@bbday It seems like you don't have the rights at this virtual server to use methods from user32.dll. What is this virtual server? I think this is not related to MahApps.

**Comment by bbday** [comment]
It is vultr vps

**Comment by punker76** [comment]
@bbday Ok, and as I said before, it's maybe not a bug by MahApps

**Comment by bbday** [comment]
Problem it is with Remote Desktop if i use teamviewer i don't have this problem.

**Comment by bbday** [comment]
It is a ramdon problem, sometimes happen sometimes not, alwasy only with remote desktop not with teamviewer. is it possible add something try / catch inside mapapp dll to not trigger exception, cause then app crash, i wanna just ignore error.

**Comment by punker76** [comment]
@bbday I will surround it with a MahAppsException
