### ISSUE TITLE
System.UnauthorizedAccessException at GlowWindow.WndProc

### ISSUE THREAD

**Issue by xmedeko** [MahApps/MahApps.Metro#2790]
I've got an error log from some machines:

System.UnauthorizedAccessException: E_ACCESSDENIED
at Standard.HRESULT.ThrowIfFailed(String message) in d:\projects\git\MahApps.Metro\MahApps.Metro\Microsoft.Windows.Shell\Standard\ErrorCodes.cs:line 616
at Standard.HRESULT.ThrowLastError() in d:\projects\git\MahApps.Metro\MahApps.Metro\Microsoft.Windows.Shell\Standard\ErrorCodes.cs:line 625
at MahApps.Metro.Controls.GlowWindow.GetRelativeMousePosition() in d:\projects\git\MahApps.Metro\MahApps.Metro\Controls\GlowWindow.xaml.cs:line 335
at MahApps.Metro.Controls.GlowWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean

I'm sorry I do not know how to reproduce the problem and even do not have a slight clue what happened, since our logs are anonymous. Also sorry that the log is truncated.

Environment:
- MahApps.Metro __v1.3.0__
- Windows __do not know__
- Visual Studio __2015__
- .NET Framework compiled with __4.5__ but do not know which is installed on the user's machine.

**Comment by punker76** [comment]
@xmedeko There is maybe something not allowed at this machines. I don't know what it is. MahApps uses some dll calls, but I think these calls are correct...

e.g. 

```csharp
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [DllImport("user32.dll", EntryPoint = "GetCursorPos", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool _GetCursorPos(out POINT lpPoint);

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public static POINT GetCursorPos()
        {
            POINT pt;
            if (!_GetCursorPos(out pt))
            {
                HRESULT.ThrowLastError();
            }

            return pt;
        }
```

**Comment by xmedeko** [comment]
Thanks for the info. I'm closing the issue and write a new one if I get more information (if the user contact our tech. support.).
