### ISSUE TITLE
GetPhysicalCursorPos

### ISSUE THREAD

**Issue by bbday** [MahApps/MahApps.Metro#2830]
i Use remotedesktop, how i can fix it?

Uups, this should not happen! Sorry for this exception! Is this maybe happend on a virtual machine or via remote desktop? Please let us know, thx.
   at MahApps.Metro.Controls.WinApiHelper.GetPhysicalCursorPos()
   at MahApps.Metro.Controls.WinApiHelper.GetRelativeMousePosition(IntPtr hWnd)
   at MahApps.Metro.Controls.GlowWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by thoemmi** [comment]
What's the version of your operating system? `GetPhysicalCursorPos` is available since Windows Vista/Windows Server 2008.

**Comment by punker76** [comment]
@thoemmi this is also interesting http://stackoverflow.com/questions/20142166/explain-errors-from-getkeystate-getcursorpos

**Comment by thoemmi** [comment]
Ok, so it seems to be general issue with remote desktop then 😒

**Comment by bbday** [comment]
Windows Server 2012 but i have same issue with W10

**Comment by garsia0** [comment]
for fix rdp problem change api for 
 private static bool _GetPhysicalCursorPos(out POINT lpPoint)
        {
            try
            {
                lpPoint.x = System.Windows.Forms.Cursor.Position.X;
                lpPoint.y = System.Windows.Forms.Cursor.Position.Y;
                return true;
            }
            catch
            {
                lpPoint = new POINT();
                return false;
            }

            
        }
