### ISSUE TITLE
System.UnauthorizedAccessException at GlowWindow.WndProc #2790 is occured on my computer

### ISSUE THREAD

**Issue by zredb** [MahApps/MahApps.Metro#2872]
I've got an error log from my machine:
Occurrence time:2017-02-28 10:50:00,773    Method name:App_DispatcherUnhandledException 
System.UnauthorizedAccessException: E_ACCESSDENIED
   at Standard.HRESULT.ThrowIfFailed(String message)
   at MahApps.Metro.Controls.GlowWindow.GetRelativeMousePosition()
   at MahApps.Metro.Controls.GlowWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

 I do not know how to reproduce the problem, and I checked the GetCursorPos implement is same as punker76 mentioned at https://github.com/MahApps/MahApps.Metro/issues/2790

Environment:

MahApps.Metro v1.3.0
Windows 10
Visual Studio 2013
.NET Framework  4.5

**Comment by punker76** [comment]
@zredb Please can you try the latest release 1.4.3? Thx.

**Comment by zredb** [comment]
@punker76  Would tell me what changed for this bug in 1.4.3?

**Comment by punker76** [comment]
@zredb https://github.com/MahApps/MahApps.Metro/commit/41fd0a491610fc6daf6c80fe4d5a7d97322db640

**Comment by punker76** [comment]
@zredb Any news for this?
