### ISSUE TITLE
Windows XP Compatibility

### ISSUE THREAD

**Issue by garsia0** [MahApps/MahApps.Metro#2973]
# PLEASE READ BEFORE POSTING AN ISSUE

This is a place for issues for MahApps itself. Questions are better asked in the [Gitter](https://gitter.im/MahApps/MahApps.Metro) room or at [stackoverflow](http://stackoverflow.com/questions/tagged/mahapps.metro).

### Seriously consider creating and linking to a test repo which takes absolutely minimal setup to illustrate how reproduce the problem.

My time is limited and .Zip files, code snippets and partial examples are often a time sink. GitHub also provides great communication and code review tools which can be utilised.

## HOW TO POST A GOOD SAMPLE.

Follow these guidelines and I will most likely look at the issue sooner:

* Post a full GitHub repository. Not a zip file, half baked snippet etc. If GitHub is new to you consider it a great learning opportunity and chance to get involved.
* The repository should have just ONE step max for me to get running, and that is "Restore NuGet Packages". If there are any other missing dependencies, or uncompiling features I will most likely move on to another issue.
* I'm not trying to be awkward. I'm just busy and I'm helping a lot of people, not just you, so help me out and I will help you out.

## What steps will reproduce this issue?

Aplication Open in some cases crash
Error Parsing Packet:Object reference not set to an instance of an object.
System.EntryPointNotFoundException: Unable to find an entry point named 'GetPhysicalCursorPos' in DLL 'user32.dll'.
   at Standard.NativeMethods._GetPhysicalCursorPos(POINT& lpPoint)
   at Standard.NativeMethods.TryGetPhysicalCursorPos(POINT& pt)
   at MahApps.Metro.Controls.WinApiHelper.TryGetRelativeMousePosition(IntPtr hWnd, Point& point)
   at MahApps.Metro.Controls.GlowWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.ITfMessagePump.GetMessageW(MSG& msg, Int32 hwnd, Int32 msgFilterMin, Int32 msgFilterMax, Boolean& result)
   at System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()

### Expected outcome

_Write expected outcome here_

### Repo

_Link to the Repo_

### Environment

- MahApps.Metro __v1.5.0.23__
- Windows OS __XP__
- Visual Studio __2010__
- .NET Framework __4.0__

**Comment by thoemmi** [comment]
Windows XP isn't supported anymore neither by Microsoft nor by Mahapps.Metro.

**Comment by garsia0** [comment]
private static bool _GetPhysicalCursorPos(out POINT lpPoint)
        {
            try
            {
                lpPoint.x = System.Windows.Forms.Cursor.Position.X;
                lpPoint.y = System.Windows.Forms.Cursor.Position.Y;
                return true;
            }
            catch
            {
                lpPoint = new POINT();
                return false;
            }

            
        }

Work for me
