### ISSUE TITLE
TryGetPhysicalCursorPos() throws exception

### ISSUE THREAD

**Issue by benjaminwinokur** [MahApps/MahApps.Metro#2981]
## What steps will reproduce this issue?
Sometimes right clicking will cause application to crash (so far only on server 2003 32 bit)

System.EntryPointNotFoundException: Unable to find an entry point named 'GetPhysicalCursorPos' in DLL 'user32.dll'.
   at Standard.NativeMethods._GetPhysicalCursorPos(POINT& lpPoint)
   at Standard.NativeMethods.TryGetPhysicalCursorPos(POINT& pt) in d:\projects\git\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.Shared\Microsoft.Windows.Shell\Standard\NativeMethods.cs:line 3057
   at MahApps.Metro.Controls.WinApiHelper.TryGetRelativeMousePosition(IntPtr hWnd, Point& point) in d:\projects\git\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.Shared\Controls\WinApiHelper.cs:line 28
   at MahApps.Metro.Controls.GlowWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in d:\projects\git\MahApps.Metro\src\MahApps.Metro\MahApps.Metro.Shared\Controls\GlowWindow.xaml.cs:line 317
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.IntWindowFromPoint(POINTSTRUCT pt)
   at MS.Win32.UnsafeNativeMethods.WindowFromPoint(Int32 x, Int32 y)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at DocGen.App.Main()
### Expected outcome
Update MahApps.Metro\src\MahApps.Metro\MahApps.Metro.Shared\Microsoft.Windows.Shell\Standard\NativeMethods.cs - TryGetPhysicalCursorPos(out POINT pt) 
to be in a try catch loop

### Repo

_none_

### Environment

- MahApps.Metro __v1.5.0__
- Windows OS __Server_2003__
- Visual Studio __2015__
- .NET Framework __4.0__

**Comment by benjaminwinokur** [comment]
[SecurityCritical]
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public static bool TryGetPhysicalCursorPos(out POINT pt)
        {
            // On windows server 2003, occasionally it will fail to find the entry point
            // Unable to find an entry point named 'GetPhysicalCursorPos' in DLL 'user32.dll'.
            // this allows the application to continue running
            try
            {
                var returnValue = _GetPhysicalCursorPos(out pt);
                // Sometimes Win32 will fail this call, such as if you are
                // not running in the interactive desktop. For example,
                // a secure screen saver may be running.
                if (returnValue)
                {
                    return returnValue;
                }

            }
            finally
            { }
            System.Diagnostics.Debug.WriteLine("GetPhysicalCursorPos failed!");
            pt.x = 0;
            pt.y = 0;
            return false;
        }

**Comment by thoemmi** [comment]
Minimum supported systems for [`GetPhysicalCursorPos`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa969464(v=vs.85).aspx) are Windows Vista and Windows Server 2008. Microsoft's extended support for Windows Server 2003 ended July 14, 2015, and so did MahApps.Metro.
