### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Nuklon** [MahApps/MahApps.Metro#3107]
On Windows 10 latest build (not the preview), latest MahApps NuGet release. If I'm closing my application, this is sometimes thrown. The stacktrace is this:

```
   at MahApps.Metro.Behaviours.WindowsSettingBehaviour.CleanUp() in C:\projects\mahapps-metro\src\MahApps.Metro\MahApps.Metro.Shared\Behaviours\WindowsSettingBehaviour.cs:line 59
   at MahApps.Metro.Behaviours.WindowsSettingBehaviour.AssociatedObject_Closed(Object sender, EventArgs e) in C:\projects\mahapps-metro\src\MahApps.Metro\MahApps.Metro.Shared\Behaviours\WindowsSettingBehaviour.cs:line 30
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by punker76** [comment]
@Nuklon The latest stable or pre-release of MahApps? Can you post the version?

**Comment by Nuklon** [comment]
Sorry, missed it, 1.6.0.184.

**Comment by punker76** [comment]
@Nuklon Do you have other closed or closing events? Or maybe some overrides for OnClosing or OnClosed? Seems like the closed event in the behavior is called twice or with a delay.

**Comment by Nuklon** [comment]
No, nothing, there's Caliburn's OnDeactivate in the main view model, but that's it (which only gets called once, I checked).
