### ISSUE TITLE
Styles/Controls.xaml appears to be missing in 0.10.1.12-ALPHA Nuget Package

### ISSUE THREAD

**Issue by capnfabs** [MahApps/MahApps.Metro#321]
When trying to load the following in the VS designer:

```
<Metro:MetroWindow x:Class="ElecNetKitExplorer.MainWindow"
        xmlns:Metro="clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow" Height="350" Width="525">
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Colours.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Fonts.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Accents/BaseLight.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Window.Resources>
    <Grid>

    </Grid>
</Metro:MetroWindow>
```

Under 0.10.0.0, everything loads fine. Under 0.10.1.12-ALPHA, the following exception is generated by the designer:

```
Exception: An error occurred while finding the resource dictionary "pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml".
at Microsoft.Expression.WpfPlatform.InstanceBuilders.ResourceDictionaryInstanceBuilder.ProvideResourceDictionary(IInstanceBuilderContext context, ViewNode viewNode, IDocumentRoot& relatedRoot, ResourceDictionary& originalInstance)
at Microsoft.Expression.WpfPlatform.InstanceBuilders.ResourceDictionaryInstanceBuilder.UpdateProperty(IInstanceBuilderContext context, ViewNode viewNode, IProperty propertyKey, DocumentNode valueNode)
at Microsoft.Expression.WpfPlatform.InstanceBuilders.ResourceDictionaryInstanceBuilder.InstantiateProperties(IInstanceBuilderContext context, ViewNode viewNode, DocumentCompositeNode compositeNode)
at Microsoft.Expression.Platform.InstanceBuilders.DictionaryInstanceBuilder.Initialize(IInstanceBuilderContext context, ViewNode viewNode, Boolean isNewInstance)
at Microsoft.Expression.Platform.InstanceBuilders.ViewNodeManager.InitializeInstance(IInstanceBuilder builder, ViewNode viewNode, Boolean isNewInstance)
```

 Copy-pasting the entire contents of Controls.xaml from source into the appropriate places in the above example works fine for 0.10.1.12-ALPHA.

 It appears that styles/Controls.xaml is corrupted, as I can find it in [Assembly Analyser](http://asmanalyzer.codeplex.com/), but when trying to export the file, exceptions are generated:

```
 System.Xaml.XamlXmlWriterException: Unable to call 'WriteEndMember' in current state.
   at System.Xaml.XamlXmlWriter.WriterState.WriteEndMember(XamlXmlWriter writer)
   at System.Xaml.XamlXmlWriter.WriterState.WriteNode(XamlXmlWriter writer, XamlNode node)
   at System.Xaml.XamlXmlWriter.TryCurlyForm.WriteNodesInXmlForm(XamlXmlWriter writer)
   at System.Xaml.XamlXmlWriter.TryCurlyForm.WriteEndMember(XamlXmlWriter writer)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.WriteDynamicResourceExtension(DynamicResourceExtension dynamicResourceExtension, XamlXmlWriter xamlWriter)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.WriteValue(Object value, XamlSchemaContext schemaContext, XamlXmlWriter xamlWriter)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.Build(XamlReader xamlReader, XamlXmlWriter xamlWriter, IList keys)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.WriteNodeList(XamlNodeList nodeList, XamlXmlWriter xamlWriter)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.WriteValue(Object value, XamlSchemaContext schemaContext, XamlXmlWriter xamlWriter)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.Build(XamlReader xamlReader, XamlXmlWriter xamlWriter, IList keys)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.WriteStream(Stream stream, XamlSchemaContext schemaContext, XamlXmlWriter xamlWriter)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.WriteValue(Object value, XamlSchemaContext schemaContext, XamlXmlWriter xamlWriter)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.Build(XamlReader xamlReader, XamlXmlWriter xamlWriter, IList keys)
   at Kokomo.PeInspector.Reflection.XamlDocumentBuilder.Build(XamlReader xamlReader, ICodeWriter writer, Assembly primaryAssembly, IAssemblyLoadContext loadContext)
   at Kokomo.PeInspector.Reflection.AssemblyAnalyzerDocumentViewModel.<>c__DisplayClass12.<GetXamlBuilder>b__11(ICodeWriter writer)
   at Kokomo.PeInspector.Reflection.SourceDocumentViewModel.SaveDocument()
   at Kokomo.DelegatedCommand.Execute(Object parameter)
```

**Comment by Andead** [comment]
Same error. I have a project of type Class Library with MahApps.Metro installed via NuGet (package version 1.2.4.0, .NET Framework 4.5).

I have created an XAML UserControl file, where I reference the ResourceDictionaries as usual:

![image](https://cloud.githubusercontent.com/assets/932798/12948437/4893c5ca-d013-11e5-943c-c5081c720452.png)

This is the designer content: 

> Exception: An error occurred while finding the resource dictionary "pack://application:,,,/MahApps.Metro;component/Styles/Controls.xaml".
 at 

> Microsoft.Expression.WpfPlatform.InstanceBuilders.ResourceDictionaryInstanceBuilder.ProvideResourceDictionary(IInstanceBuilderContext context, ViewNode viewNode, IDocumentRoot& relatedRoot, ResourceDictionary& originalInstance)
>    at Microsoft.Expression.WpfPlatform.InstanceBuilders.ResourceDictionaryInstanceBuilder.UpdateProperty(IInstanceBuilderContext context, ViewNode viewNode, IProperty propertyKey, DocumentNode valueNode)
>    at Microsoft.Expression.WpfPlatform.InstanceBuilders.ResourceDictionaryInstanceBuilder.InstantiateProperties(IInstanceBuilderContext context, ViewNode viewNode, DocumentCompositeNode compositeNode)
>    at Microsoft.Expression.Platform.InstanceBuilders.DictionaryInstanceBuilder.Initialize(IInstanceBuilderContext context, ViewNode viewNode, Boolean isNewInstance)
>    at Microsoft.Expression.Platform.InstanceBuilders.ViewNodeManager.InitializeInstance(IInstanceBuilder builder, ViewNode viewNode, Boolean isNewInstance)

The styles and controls work perfectly at compile time, but I cannot see anything in designer. Tried removing MahApps.Metro package and installing it again, restarting Visual Studio, but nothing solved the problem.

Visual Studio Professional 2013 Update 5, Windows 7 x64.

**Comment by Vrielmann-EE** [comment]
@Andead-zz : 4 years later, still the same problems :(

Did you solved your problem?

**Comment by punker76** [comment]
@Vrielmann-EE I don't think it's exactly the same problem. If you have a problem with the designer, in **which** Visual Studio? What version of MahApps? What is the **stacktrace**? Create a new issue!
