### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by Araym87** [MahApps/MahApps.Metro#3301]
Hi all, i am reporting an issue, which happens rarely for few of my users. I am using MahApps.Metro version 1.6.0.0

I was googling and found a few very similar topics, but with different stack trace, so i think it is another place, which can cause this error. Could you please check it? Thank you

StackTrace:
Exception:
System.OverflowException: Arithmetic operation resulted in an overflow.
at Microsoft.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled) in d:\projects\git\MahApps.Metro\MahApps.Metro\Microsoft.Windows.Shell\WindowChromeWorker.cs:line 871
at Microsoft.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in d:\projects\git\MahApps.Metro\MahApps.Metro\Microsoft.Windows.Shell\WindowChromeWorker.cs:line 613
at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Arithmetic operation resulted in an overflow.

**Comment by batzen** [comment]
@Araym87 Could you try to reproduce this using the latest version of MahApps.Metro?
