### ISSUE TITLE
NRE in Metro window

### ISSUE THREAD

**Issue by zinar** [MahApps/MahApps.Metro#3357]
(Very rarely) when my machine resumes from sleep if a metro windows is open and in focus it would crash with the following stack trace:
>System.NullReferenceException: Object reference not set to an instance of an object.
   at MahApps.Metro.Behaviours.BorderlessWindowBehavior.<OnAttached>b__10_0()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Window.OnDeactivated(EventArgs e)
   at System.Windows.Window.HandleActivate(Boolean windowActivated)
   at System.Windows.Window.WmActivate(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)`

 - MahApps.Metro version [e.g. v1.5.0]
 - OS: Win10 1803
 - .NET Framework 4.6.2

**Comment by punker76** [comment]
@zinar I mean that this one is fixed in later version like v1.6.5
