### ISSUE TITLE
not support the xp

### ISSUE THREAD

**Issue by Linkzd** [MahApps/MahApps.Metro#3384]
not support the xp

========================================
Time:2018-11-29 09:55:31:837
Message:UI线程崩溃
Exception:System.EntryPointNotFoundException: Unable to find an entry point named 'GetPhysicalCursorPos' in DLL 'user32.dll'.
   at ControlzEx.Standard.NativeMethods._GetPhysicalCursorPos(POINT& lpPoint)
   at ControlzEx.Standard.NativeMethods.TryGetPhysicalCursorPos(POINT& pt)
   at MahApps.Metro.Controls.WinApiHelper.TryGetRelativeMousePosition(IntPtr hWnd, Point& point)
   at MahApps.Metro.Controls.GlowWindow.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
HelpLink:
HResult:

**Comment by punker76** [comment]
@Linkzd XP is no longer supported.
