### ISSUE TITLE
TaskCanceledException when opening a childwindow in new thread twice

### ISSUE THREAD

**Issue by Ksdmg** [MahApps/MahApps.Metro#3912]
## Describe the bug

When opening a new child window in a new STA thread, everything works fine the first time. When you close the child window and reopen it using a new thread, a TaskCanceledException is thrown. Here is the callstack:
```
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at MahApps.Metro.Controls.Extensions.Invoke(DispatcherObject dispatcherObject, Action invokeAction) in /_/src/MahApps.Metro/Controls/Extensions.cs:line 56
   at MahApps.Metro.Controls.MetroWindow.ThemeManagerOnIsThemeChanged(Object sender, ThemeChangedEventArgs e) in /_/src/MahApps.Metro/Controls/MetroWindow.cs:line 1094
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at ControlzEx.Theming.ThemeManager.OnThemeChanged(Object target, ResourceDictionary targetResourceDictionary, Theme oldTheme, Theme newTheme) in C:\projects\controlzex\src\ControlzEx\Theming\ThemeManager.cs:line 1163
   at ControlzEx.Theming.ThemeManager.ChangeTheme(Object target, ResourceDictionary resourceDictionary, Theme oldTheme, Theme newTheme) in C:\projects\controlzex\src\ControlzEx\Theming\ThemeManager.cs:line 642
   at ControlzEx.Theming.ThemeManager.ChangeTheme(FrameworkElement frameworkElement, Theme newTheme) in C:\projects\controlzex\src\ControlzEx\Theming\ThemeManager.cs:line 545
   at ControlzEx.Theming.ThemeManager.ChangeTheme(FrameworkElement frameworkElement, String themeName, Boolean highContrast) in C:\projects\controlzex\src\ControlzEx\Theming\ThemeManager.cs:line 502
   at MahAppsThreadAccess.ChildWindow..ctor() in C:\Users\schaafa\source\repos\MahAppsThreadAccess\MahAppsThreadAccess\ChildWindow.xaml.cs:line 26
   at MahAppsThreadAccess.MainWindow.<Button_Click>b__1_0(Object x) in C:\Users\schaafa\source\repos\MahAppsThreadAccess\MahAppsThreadAccess\MainWindow.xaml.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

## Steps to reproduce

1.  Clone repo: https://github.com/Ksdmg/MahAppsThreadAccess
2. Open child window using the button
3. Close child window
4. Open child window again using the button

## Environment

```
MahApps.Metro version: v2.2.0
Visual Studio: 2019 16.7.2
Target Framework: .Net v4.7.2
```

**Comment by punker76** [comment]
@Ksdmg I tested your sample with the latest version v2.3.4 I found that you call `InvokeShutdown` inside the closed event of the child window. You have 2 options to solve this, don't do this, or use the `BeginInvokeShutdown`.

```
private void Child_Closed(object sender, EventArgs e)
{
    ((ChildWindow)sender).Closed -= Child_Closed;
    ((ChildWindow)sender).Dispatcher.BeginInvokeShutdown(DispatcherPriority.Background);
}
```
