### ISSUE TITLE
The requested lookup key was not found in any active activation context

### ISSUE THREAD

**Issue by myCollections** [MahApps/MahApps.Metro#3922]
## Describe the bug

Hello, since last version i receive this error message the first time the application is launched :

The requested lookup key was not found in any active activation context

Stack trace : 

at MahApps.Metro.Controls.WinApiHelper.GetWindowText(Window window)
   at MahApps.Metro.Automation.Peers.MetroWindowAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.Process_WM_SIZE(UIElement rootUIElement, IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Interop.HwndSource.LayoutFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

## Environment

MahApps.Metro version: v2.2.0
Target Framework: .Net v4.6.1

**Comment by punker76** [comment]
@myCollections Can you show your problem with a simple application? Never seen this issue, so maybe something special.

**Comment by myCollections** [comment]
Thanks for your quick reply.
You can try it with this : http://www.mycollections.fr/Download/myCollections.exe

But it will happens only twice on the same computer.
So difficult to reproduce.

**Comment by mohdimas** [comment]
I have similar issues in our production with similar stacktrace, e.g.
```System.ComponentModel.Win32Exception (0x80004005): Too many posts were made to a semaphore
at MahApps.Metro.Controls.WinApiHelper.GetWindowText(Window window)```
or 
```System.ComponentModel.Win32Exception (0x80004005): Attempt to release mutex not owned by caller
at MahApps.Metro.Controls.WinApiHelper.GetWindowText(Window window)```

I'm wondering whether this Exception will be caught somewhere https://github.com/MahApps/MahApps.Metro/blob/develop/src/MahApps.Metro/Controls/WinApiHelper.cs#L62 ?

**Comment by timunie** [comment]
@myCollections @mohdimas it may be helpful to get direct access to your source code in order to debug it. Maybe you can share it at least private to @punker76 if you don't want to make it public. If possible a stripped down sample (source) would also be useful if it shows your issue. 

Thank you in advance and happy coding 
Tim

**Comment by enricogior** [comment]
It's also happening to some users when trying to open the FancyZones editor in PowerToys
https://github.com/microsoft/PowerToys/issues/6946

**Comment by enricogior** [comment]
@punker76 
thanks for the fix.
We will release PowerToys 0.25 next week and it will use the updated version.

**Comment by myCollections** [comment]
@punker76 Thanks a lot for the Fix 👍
