### ISSUE TITLE
Can't find ressource on Dema app

### ISSUE THREAD

**Issue by myCollections** [MahApps/MahApps.Metro#4004]
Hello,

When i try to compile the demo app at get this error :

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message='La propriété Set 'System.Windows.ResourceDictionary.Source' a levé une exception.' numéro de ligne '12' et position de ligne '18'.
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at MetroDemo.App.InitializeComponent() in E:\MahApps.Metro-develop\MahApps.Metro-develop\src\MahApps.Metro.Samples\MahApps.Metro.Demo\App.xaml:line 1
   at MetroDemo.App.Main()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
IOException: Impossible de trouver la ressource 'styles/themes/light.blue.xaml'.

**Comment by punker76** [comment]
@myCollections You must compile the solution of this repo.

**Comment by myCollections** [comment]
> 
> 
> @myCollections You must compile the solution of this repo.

Hello,

Thanks for the quick reply.
I get a clone zip of the repo.
And made a rebuild all.

**Comment by punker76** [comment]
@myCollections Have you all necessary SDKs installed? https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution

**Comment by myCollections** [comment]
> 
> 
> @myCollections Have you all necessary SDKs installed? https://github.com/MahApps/MahApps.Metro/wiki/Building-the-MahApps.Metro-solution

Yes From 2.1.602 to 5.0.10 for core
And 4.7 for Framework.

First time i get any issues.

**Comment by punker76** [comment]
@myCollections Then sorry that I can not help you, but IMO it's not related to MahApps or this repo.

**Comment by myCollections** [comment]
Not sure as i i comment this line in app.xaml

<ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Light.Blue.xaml" />

Everything is working fine. Just ugly :)
