### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException: 'A task was canceled.'

### ISSUE THREAD

**Issue by erotavlas** [MahApps/MahApps.Metro#4085]
When I try to change the them from code behind (from within the Execute of a Command) I get the following error (see end of post)

I'm using version 2.4.3 of mahapps but was also getting an exception in 1.6.0 when attempting the same action, however the error was different.  It was pointing to a threading issue.

The llocation I'm trying to change the them is here

```
    public class ChangeThemeCommand : ICommand
    {
        public event EventHandler CanExecuteChanged;

        public bool CanExecute(object parameter)
        {
            return true;
        }

        public void Execute(object parameter)
        {
            string name = (string)parameter;
           
            ThemeManager.Current.ChangeThemeBaseColor(Application.Current, name);
        }
    }
```
That command is being called from the main window from a menu item like this

```
            <MenuItem Header="Theme"  >
                <MenuItem Header="Light" Icon="{icons:FontAwesome Kind=CircleRegular,Width=25}" Command="{Binding changeThemeCommand}" CommandParameter="Light" ></MenuItem>
                <MenuItem Header="Dark" Icon="{icons:FontAwesome Kind=CircleSolid, Width=25}" Command="{Binding changeThemeCommand}" CommandParameter="Dark" ></MenuItem>
            </MenuItem>
```

My app initialization in App.cs looks like this

```
                Thread splashScreenWindowThread = new Thread(() =>
                {
                    splashScreenWindow = container.Resolve<SplashScreen>();
                    splashScreenWindow.Show();

                    System.Windows.Threading.Dispatcher.Run();

                });
                splashScreenWindowThread.SetApartmentState(ApartmentState.STA);
                splashScreenWindowThread.IsBackground = true;
                splashScreenWindowThread.Start();

                var mainwindow = container.Resolve<MainWindow>();
                this.MainWindow = mainwindow;

                mainwindow.Loaded += (s, ev) =>
                {
                    splashScreenWindow.Dispatcher.Invoke(new System.Action(
                    () =>
                    {
                        if (splashScreenWindow.IsActive)
                            splashScreenWindow.Close();

                        splashScreenWindow.Dispatcher.InvokeShutdown();
                    }

                    ));
                };
                mainwindow.Show();
```
ERROR

    System.Threading.Tasks.TaskCanceledException: 'A task was canceled.'

```
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at ControlzEx.Theming.ThemeManager.ChangeTheme(Object target, ResourceDictionary resourceDictionary, Theme oldTheme, Theme newTheme) in /_/src/ControlzEx/Theming/ThemeManager.cs:line 636
   at ControlzEx.Theming.ThemeManager.ChangeTheme(Object target, ResourceDictionary resourceDictionary, Theme oldTheme, String baseColorScheme, String colorScheme) in /_/src/ControlzEx/Theming/ThemeManager.cs:line 741
   at ControlzEx.Theming.ThemeManager.ChangeThemeBaseColor(Object target, ResourceDictionary resourceDictionary, Theme oldTheme, String baseColorScheme) in /_/src/ControlzEx/Theming/ThemeManager.cs:line 840
   at ControlzEx.Theming.ThemeManager.ChangeThemeBaseColor(Application app, String baseColorScheme) in /_/src/ControlzEx/Theming/ThemeManager.cs:line 769
   at MyAppName.Commands.ChangeThemeCommand.Execute(Object parameter) in D:\SOURCECODE\VISUALSTUDIO\EngineeringTools\MyApp\DEV-branch\MyAppName\Commands\ChangeThemeCommand.cs:line 26
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at MyAppName.App.Main()
```

**Comment by punker76** [comment]
@erotavlas This issue happens with windows that are created in a different thread and then not closing correctly. I suggest to use this line of code to call the dispatcher shutdown

```
splashScreenWindow.Dispatcher.BeginInvokeShutdown(DispatcherPriority.Background);
```

**Comment by punker76** [comment]
I had another look at this against today's sources, and what I wrote above still holds.

First the reproduction: a `MetroWindow` on a thread of its own, closed and then `Dispatcher.InvokeShutdown()`, and the next `ChangeThemeBaseColor` throws with the same stack you posted, through `MetroWindow.HandleThemeManagerThemeChanged`.

The reason shows up once you watch that window's `Unloaded` event. A `MetroWindow` subscribes to `ThemeManager.ThemeChanged` when it loads and lets go of it again when it unloads. `InvokeShutdown()` takes the dispatcher down right away, `Unloaded` never runs, and the window stays on the event with a dispatcher that cannot take work any more. The next theme change calls into it, and that is the cancelled task.

`BeginInvokeShutdown(DispatcherPriority.Background)` queues the shutdown behind the work already waiting, so `Unloaded` gets to run, the window lets go, and the theme change goes through. Measured on current `develop`:

| how the second thread is taken down | `Unloaded` ran | changing the theme |
| --- | --- | --- |
| `Dispatcher.InvokeShutdown()` | no | throws `TaskCanceledException` |
| `Dispatcher.BeginInvokeShutdown(DispatcherPriority.Background)` | yes | goes through |
| closing the window, leaving the dispatcher alone | yes | goes through |

Closing this one. If it comes back with that call in place, please open a new issue with a small sample, because then it would be something else.
