### ISSUE TITLE
Application start fails due to dependency conflict between MahApps.Metro 2.4.10 and ControlEx 6.0.0

### ISSUE THREAD

**Issue by coder-thorsten** [MahApps/MahApps.Metro#4489]
## Describe the bug

The start of our ClickOnce application fails. The stacktrace in the eventlog gives the information, that MahApps.Metro uses the field "ControlzEx.Behaviors.WindowChromeBehavior.TryToBeFlickerFreeProperty" which was removed from ControlEx in version 6.0.0.

## Steps to reproduce

A wpf Clickonce application that uses MetroWindow as Window/Control
When starting, the application fails.

## Expected behavior

Application should start

## Actual behavior

Application does not start

## Environment

```
MahApps.Metro version: v2.4.10
ControlEx version: 6.0.0
Windows build number: Win10 22H2 [Version 10.0.19045.4412]
Visual Studio: 2022 17.9.7
Target Framework: .Net 8 (8.0.5)
```

## Stacktrace

CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'xxx.MainWindow' that matches the specified binding constraints threw an exception.
 ---> System.MissingFieldException: Field not found: 'ControlzEx.Behaviors.WindowChromeBehavior.TryToBeFlickerFreeProperty'.
   at MahApps.Metro.Behaviors.BorderlessWindowBehavior.OnAttached()
   at Microsoft.Xaml.Behaviors.Behavior.Attach(DependencyObject dependencyObject)
   at Microsoft.Xaml.Behaviors.BehaviorCollection.ItemAdded(Behavior item)
   at Microsoft.Xaml.Behaviors.AttachableCollection`1.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.FreezableCollection`1.OnCollectionChanged(NotifyCollectionChangedAction action, Int32 oldIndex, T oldValue, Int32 newIndex, T newValue)
   at System.Windows.FreezableCollection`1.AddHelper(T value)
   at System.Windows.FreezableCollection`1.Add(T value)
   at MahApps.Metro.Controls.MetroWindow.InitializeWindowChromeBehavior()
   at MahApps.Metro.Controls.MetroWindow..ctor()
   at xxx.MainWindow..ctor() in /source/xxx/MainWindow.xaml.cs:line 27

**Comment by coder-thorsten** [comment]
@timunie thank you for the answer. I will downgrade ControlzEx and wait for v3

**Comment by timunie** [comment]
please close the issue.
